{
	"document_title": "Security update for python-keystoneclient",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2015:1208-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2015-05-13T09:07:38Z",
				"description": "current"
			}
		},
		"initial_release_date": "2015-05-13T09:07:38Z",
		"current_release_date": "2015-05-13T09:07:38Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-keystoneclient",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "The python-keystoneclient was updated to fix one security issues.\n\nThe following vulnerability was fixed:\n- bsc#928205: S3Token TLS cert verification option not honored (CVE-2015-1852)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-SLE12-CLOUD-5-2015-303",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20151208-1/",
			"description": "Link for SUSE-SU-2015:1208-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2015-July/001487.html",
			"description": "E-Mail link for SUSE-SU-2015:1208-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/928205",
			"description": "SUSE Bug 928205"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2015-1852/",
			"description": "SUSE CVE CVE-2015-1852 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
						"full_product_name": {
							"text": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
							"product_id": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5",
							"cpe": "cpe:/o:suse:suse-sle12-cloud-compute:5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-keystoneclient-1.0.0-16.1",
				"full_product_name": {
					"text": "python-keystoneclient-1.0.0-16.1",
					"product_id": "python-keystoneclient-1.0.0-16.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-keystoneclient-doc-1.0.0-16.1",
				"full_product_name": {
					"text": "python-keystoneclient-doc-1.0.0-16.1",
					"product_id": "python-keystoneclient-doc-1.0.0-16.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-keystoneclient-1.0.0-16.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5"
			},
			{
				"product_reference": "python-keystoneclient-doc-1.0.0-16.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "The s3_token middleware in OpenStack keystonemiddleware before 1.6.0 and python-keystoneclient before 1.4.0 disables certification verification when the \"insecure\" option is set in a paste configuration (paste.ini) file regardless of the value, which allows remote attackers to conduct man-in-the-middle attacks via a crafted certificate, a different vulnerability than CVE-2014-7144.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2015-1852",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-keystoneclient-1.0.0-16.1",
						"SUSE Cloud Compute Node for SUSE Linux Enterprise 12 5:python-keystoneclient-doc-1.0.0-16.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20151208-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2015-1852.html",
					"description": "CVE-2015-1852"
				},
				{
					"url": "https://bugzilla.suse.com/928205",
					"description": "SUSE Bug 928205"
				}
			]
		}
	]
}
