{
	"document_title": "Security update for python",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2019:1273-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2019-04-25T13:55:15Z",
				"description": "current"
			}
		},
		"initial_release_date": "2019-04-25T13:55:15Z",
		"current_release_date": "2019-04-25T13:55:15Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python fixes the following issues:\n\nSecurity issues fixed:\n\n- CVE-2019-9948: Fixed a 'file:' blacklist bypass in URIs by using the 'local-file:' scheme instead (bsc#1130847).\n- CVE-2019-9636: Fixed an information disclosure because of incorrect handling of Unicode encoding during NFKC normalization (bsc#1129346).\n\nThis update was imported from the SUSE:SLE-15:Update update project.",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-2019-1273",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html",
			"description": "E-Mail link for openSUSE-SU-2019:1273-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1129346",
			"description": "SUSE Bug 1129346"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1130847",
			"description": "SUSE Bug 1130847"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2019-9636/",
			"description": "SUSE CVE CVE-2019-9636 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2019-9948/",
			"description": "SUSE CVE CVE-2019-9948 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.0",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.0",
						"full_product_name": {
							"text": "openSUSE Leap 15.0",
							"product_id": "openSUSE Leap 15.0",
							"cpe": "cpe:/o:opensuse:leap:15.0"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-2.7.14-lp150.6.10.1",
				"full_product_name": {
					"text": "python-2.7.14-lp150.6.10.1",
					"product_id": "python-2.7.14-lp150.6.10.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-32bit-2.7.14-lp150.6.10.1",
				"full_product_name": {
					"text": "python-32bit-2.7.14-lp150.6.10.1",
					"product_id": "python-32bit-2.7.14-lp150.6.10.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-curses-2.7.14-lp150.6.10.1",
				"full_product_name": {
					"text": "python-curses-2.7.14-lp150.6.10.1",
					"product_id": "python-curses-2.7.14-lp150.6.10.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-demo-2.7.14-lp150.6.10.1",
				"full_product_name": {
					"text": "python-demo-2.7.14-lp150.6.10.1",
					"product_id": "python-demo-2.7.14-lp150.6.10.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-gdbm-2.7.14-lp150.6.10.1",
				"full_product_name": {
					"text": "python-gdbm-2.7.14-lp150.6.10.1",
					"product_id": "python-gdbm-2.7.14-lp150.6.10.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-idle-2.7.14-lp150.6.10.1",
				"full_product_name": {
					"text": "python-idle-2.7.14-lp150.6.10.1",
					"product_id": "python-idle-2.7.14-lp150.6.10.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-tk-2.7.14-lp150.6.10.1",
				"full_product_name": {
					"text": "python-tk-2.7.14-lp150.6.10.1",
					"product_id": "python-tk-2.7.14-lp150.6.10.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-2.7.14-lp150.6.10.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			},
			{
				"product_reference": "python-32bit-2.7.14-lp150.6.10.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			},
			{
				"product_reference": "python-curses-2.7.14-lp150.6.10.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			},
			{
				"product_reference": "python-demo-2.7.14-lp150.6.10.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			},
			{
				"product_reference": "python-gdbm-2.7.14-lp150.6.10.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			},
			{
				"product_reference": "python-idle-2.7.14-lp150.6.10.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			},
			{
				"product_reference": "python-tk-2.7.14-lp150.6.10.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.0"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "Python 2.7.x through 2.7.16 and 3.x through 3.7.2 is affected by: Improper Handling of Unicode Encoding (with an incorrect netloc) during NFKC normalization. The impact is: Information disclosure (credentials, cookies, etc. that are cached against a given hostname). The components are: urllib.parse.urlsplit, urllib.parse.urlparse. The attack vector is: A specially crafted URL could be incorrectly parsed to locate cookies or authentication data and send that information to a different host than when parsed correctly. This is fixed in: v2.7.17, v2.7.17rc1, v2.7.18, v2.7.18rc1; v3.5.10, v3.5.10rc1, v3.5.7, v3.5.8, v3.5.8rc1, v3.5.8rc2, v3.5.9; v3.6.10, v3.6.10rc1, v3.6.11, v3.6.11rc1, v3.6.12, v3.6.9, v3.6.9rc1; v3.7.3, v3.7.3rc1, v3.7.4, v3.7.4rc1, v3.7.4rc2, v3.7.5, v3.7.5rc1, v3.7.6, v3.7.6rc1, v3.7.7, v3.7.7rc1, v3.7.8, v3.7.8rc1, v3.7.9.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2019-9636",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.0:python-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-32bit-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-curses-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-demo-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-gdbm-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-idle-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-tk-2.7.14-lp150.6.10.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:P/I:N/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2019-9636.html",
					"description": "CVE-2019-9636"
				},
				{
					"url": "https://bugzilla.suse.com/1129346",
					"description": "SUSE Bug 1129346"
				},
				{
					"url": "https://bugzilla.suse.com/1135433",
					"description": "SUSE Bug 1135433"
				},
				{
					"url": "https://bugzilla.suse.com/1138459",
					"description": "SUSE Bug 1138459"
				},
				{
					"url": "https://bugzilla.suse.com/1145004",
					"description": "SUSE Bug 1145004"
				}
			]
		},
		{
			"notes": [
				{
					"text": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2019-9948",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.0:python-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-32bit-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-curses-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-demo-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-gdbm-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-idle-2.7.14-lp150.6.10.1",
						"openSUSE Leap 15.0:python-tk-2.7.14-lp150.6.10.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "low"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "6.4",
					"vector_v_2": "AV:N/AC:L/Au:N/C:P/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "3.3",
					"vector_v_3": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/opensuse-security-announce/2019-04/msg00092.html"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2019-9948.html",
					"description": "CVE-2019-9948"
				},
				{
					"url": "https://bugzilla.suse.com/1130847",
					"description": "SUSE Bug 1130847"
				},
				{
					"url": "https://bugzilla.suse.com/1135433",
					"description": "SUSE Bug 1135433"
				}
			]
		}
	]
}
