{
	"document_title": "Security update for python-docker",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE-SU-2024:2182-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-06-24T14:25:25Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-06-24T14:25:25Z",
		"current_release_date": "2024-06-24T14:25:25Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-docker",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-docker fixes the following issues:\n\n- CVE-2024-35195: Fixed missing certificate verification (bsc#1224788).\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "SUSE-2024-2182,SUSE-SLE-Manager-Tools-15-2024-2182",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242182-1/",
			"description": "Link for SUSE-SU-2024:2182-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2024-June/018806.html",
			"description": "E-Mail link for SUSE-SU-2024:2182-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1224788",
			"description": "SUSE Bug 1224788"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-35195/",
			"description": "SUSE CVE CVE-2024-35195 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Manager Tools 15",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Manager Tools 15",
						"full_product_name": {
							"text": "SUSE Manager Tools 15",
							"product_id": "SUSE Manager Tools 15",
							"cpe": "cpe:/o:suse:sle-manager-tools:15"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python2-docker-2.6.1-150000.4.3.1",
				"full_product_name": {
					"text": "python2-docker-2.6.1-150000.4.3.1",
					"product_id": "python2-docker-2.6.1-150000.4.3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-docker-2.6.1-150000.4.3.1",
				"full_product_name": {
					"text": "python3-docker-2.6.1-150000.4.3.1",
					"product_id": "python3-docker-2.6.1-150000.4.3.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python3-docker-2.6.1-150000.4.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Manager Tools 15"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-35195",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Manager Tools 15:python3-docker-2.6.1-150000.4.3.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "6",
					"vector_v_3": "CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://www.suse.com/support/update/announcement/2024/suse-su-20242182-1/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-35195.html",
					"description": "CVE-2024-35195"
				},
				{
					"url": "https://bugzilla.suse.com/1224788",
					"description": "SUSE Bug 1224788"
				}
			]
		}
	]
}
