{
	"document_title": "Security update for python-GitPython",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2023:0271-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2023-09-25T22:02:02Z",
				"description": "current"
			}
		},
		"initial_release_date": "2023-09-25T22:02:02Z",
		"current_release_date": "2023-09-25T22:02:02Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-GitPython",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-GitPython fixes the following issues:\n\n- CVE-2023-41040: Fixed directory traversal attack vulnerability (boo#1214810)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-2023-271",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/7CNHID7WWGH3NBQ4RDHSFLO7MHMZZ4ZQ/",
			"description": "E-Mail link for openSUSE-SU-2023:0271-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1214810",
			"description": "SUSE Bug 1214810"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2023-41040/",
			"description": "SUSE CVE CVE-2023-41040 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Package Hub 15 SP4",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Package Hub 15 SP4",
						"full_product_name": {
							"text": "SUSE Package Hub 15 SP4",
							"product_id": "SUSE Package Hub 15 SP4"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.4",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.4",
						"full_product_name": {
							"text": "openSUSE Leap 15.4",
							"product_id": "openSUSE Leap 15.4",
							"cpe": "cpe:/o:opensuse:leap:15.4"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python3-GitPython-3.1.12.1610074031.f653af66-bp154.2.3.1",
				"full_product_name": {
					"text": "python3-GitPython-3.1.12.1610074031.f653af66-bp154.2.3.1",
					"product_id": "python3-GitPython-3.1.12.1610074031.f653af66-bp154.2.3.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python3-GitPython-3.1.12.1610074031.f653af66-bp154.2.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Package Hub 15 SP4"
			},
			{
				"product_reference": "python3-GitPython-3.1.12.1610074031.f653af66-bp154.2.3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.4"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": " GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has not yet been addressed.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2023-41040",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Package Hub 15 SP4:python3-GitPython-3.1.12.1610074031.f653af66-bp154.2.3.1",
						"openSUSE Leap 15.4:python3-GitPython-3.1.12.1610074031.f653af66-bp154.2.3.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "low"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "4",
					"vector_v_3": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/7CNHID7WWGH3NBQ4RDHSFLO7MHMZZ4ZQ/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2023-41040.html",
					"description": "CVE-2023-41040"
				},
				{
					"url": "https://bugzilla.suse.com/1214810",
					"description": "SUSE Bug 1214810"
				}
			]
		}
	]
}
