{
	"document_title": "python38-3.8.19-8.1 on GA media",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2024:14296-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-08-29T00:00:00Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-08-29T00:00:00Z",
		"current_release_date": "2024-08-29T00:00:00Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "python38-3.8.19-8.1 on GA media",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "These are all security issues fixed in the python38-3.8.19-8.1 package on the GA media of openSUSE Tumbleweed.",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-Tumbleweed-2024-14296",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2024-8088/",
			"description": "SUSE CVE CVE-2024-8088 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python38-3.8.19-8.1",
				"full_product_name": {
					"text": "python38-3.8.19-8.1",
					"product_id": "python38-3.8.19-8.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-curses-3.8.19-8.1",
				"full_product_name": {
					"text": "python38-curses-3.8.19-8.1",
					"product_id": "python38-curses-3.8.19-8.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-dbm-3.8.19-8.1",
				"full_product_name": {
					"text": "python38-dbm-3.8.19-8.1",
					"product_id": "python38-dbm-3.8.19-8.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-idle-3.8.19-8.1",
				"full_product_name": {
					"text": "python38-idle-3.8.19-8.1",
					"product_id": "python38-idle-3.8.19-8.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-tk-3.8.19-8.1",
				"full_product_name": {
					"text": "python38-tk-3.8.19-8.1",
					"product_id": "python38-tk-3.8.19-8.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python38-3.8.19-8.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-curses-3.8.19-8.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-dbm-3.8.19-8.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-idle-3.8.19-8.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-tk-3.8.19-8.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-8088",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python38-3.8.19-8.1",
						"openSUSE Tumbleweed:python38-curses-3.8.19-8.1",
						"openSUSE Tumbleweed:python38-dbm-3.8.19-8.1",
						"openSUSE Tumbleweed:python38-idle-3.8.19-8.1",
						"openSUSE Tumbleweed:python38-tk-3.8.19-8.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {
					"base_score_v_3": "5.3",
					"vector_v_3": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2024-8088.html",
					"description": "CVE-2024-8088"
				},
				{
					"url": "https://bugzilla.suse.com/1229704",
					"description": "SUSE Bug 1229704"
				}
			]
		}
	]
}
