{
	"document_title": "python36-jupyter-server-1.10.2-1.2 on GA media",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2024:11233-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2024-06-15T00:00:00Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-06-15T00:00:00Z",
		"current_release_date": "2024-06-15T00:00:00Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "python36-jupyter-server-1.10.2-1.2 on GA media",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "These are all security issues fixed in the python36-jupyter-server-1.10.2-1.2 package on the GA media of openSUSE Tumbleweed.",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-Tumbleweed-2024-11233",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2020-26232/",
			"description": "SUSE CVE CVE-2020-26232 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python36-jupyter-server-1.10.2-1.2",
				"full_product_name": {
					"text": "python36-jupyter-server-1.10.2-1.2",
					"product_id": "python36-jupyter-server-1.10.2-1.2"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-jupyter-server-1.10.2-1.2",
				"full_product_name": {
					"text": "python38-jupyter-server-1.10.2-1.2",
					"product_id": "python38-jupyter-server-1.10.2-1.2"
				}
			},
			{
				"type": "Product Version",
				"name": "python39-jupyter-server-1.10.2-1.2",
				"full_product_name": {
					"text": "python39-jupyter-server-1.10.2-1.2",
					"product_id": "python39-jupyter-server-1.10.2-1.2"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python36-jupyter-server-1.10.2-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-jupyter-server-1.10.2-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python39-jupyter-server-1.10.2-1.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "Jupyter Server before version 1.0.6 has an Open redirect vulnerability. A maliciously crafted link to a jupyter server could redirect the browser to a different website. All jupyter servers are technically affected, however, these maliciously crafted links can only be reasonably made for known jupyter server hosts. A link to your jupyter server may appear safe, but ultimately redirect to a spoofed server on the public internet.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2020-26232",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python36-jupyter-server-1.10.2-1.2",
						"openSUSE Tumbleweed:python38-jupyter-server-1.10.2-1.2",
						"openSUSE Tumbleweed:python39-jupyter-server-1.10.2-1.2"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5.5",
					"vector_v_2": "AV:N/AC:L/Au:S/C:P/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.4",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					}
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2020-26232.html",
					"description": "CVE-2020-26232"
				},
				{
					"url": "https://bugzilla.suse.com/1179413",
					"description": "SUSE Bug 1179413"
				}
			]
		}
	]
}
