{
	"document_title": "Security update for nextcloud",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2021:0262-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2021-02-08T11:05:25Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-02-08T11:05:25Z",
		"current_release_date": "2021-02-08T11:05:25Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for nextcloud",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for nextcloud fixes the following issues:\n\n- nextcloud was upgraded to version 20.0.7\n   - CVE-2020-8294: Fixed a missing link validation (boo#1181803)\n   - CVE-2020-8295: Fixed a denial of service attack (boo#1181804)\n   - CVE-2020-8293: Fixed an input validation issue (boo#1181445)\n",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-2021-262",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/RL6T5BYT4RSAM4DNXPXTDKBKHKKNDVHW/",
			"description": "E-Mail link for openSUSE-SU-2021:0262-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1181445",
			"description": "SUSE Bug 1181445"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1181803",
			"description": "SUSE Bug 1181803"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1181804",
			"description": "SUSE Bug 1181804"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2020-8293/",
			"description": "SUSE CVE CVE-2020-8293 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2020-8294/",
			"description": "SUSE CVE CVE-2020-8294 page"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2020-8295/",
			"description": "SUSE CVE CVE-2020-8295 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.2",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.2",
						"full_product_name": {
							"text": "openSUSE Leap 15.2",
							"product_id": "openSUSE Leap 15.2",
							"cpe": "cpe:/o:opensuse:leap:15.2"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "nextcloud-20.0.7-lp152.3.6.1",
				"full_product_name": {
					"text": "nextcloud-20.0.7-lp152.3.6.1",
					"product_id": "nextcloud-20.0.7-lp152.3.6.1"
				}
			},
			{
				"type": "Product Version",
				"name": "nextcloud-apache-20.0.7-lp152.3.6.1",
				"full_product_name": {
					"text": "nextcloud-apache-20.0.7-lp152.3.6.1",
					"product_id": "nextcloud-apache-20.0.7-lp152.3.6.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "nextcloud-20.0.7-lp152.3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.2"
			},
			{
				"product_reference": "nextcloud-apache-20.0.7-lp152.3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.2"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "A missing input validation in Nextcloud Server before 20.0.2, 19.0.5, 18.0.11 allows users to store unlimited data in workflow rules causing load and potential DDoS on later interactions and usage with those rules.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2020-8293",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.2:nextcloud-20.0.7-lp152.3.6.1",
						"openSUSE Leap 15.2:nextcloud-apache-20.0.7-lp152.3.6.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4",
					"vector_v_2": "AV:N/AC:L/Au:S/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "6.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/RL6T5BYT4RSAM4DNXPXTDKBKHKKNDVHW/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2020-8293.html",
					"description": "CVE-2020-8293"
				},
				{
					"url": "https://bugzilla.suse.com/1181445",
					"description": "SUSE Bug 1181445"
				}
			]
		},
		{
			"notes": [
				{
					"text": "A missing link validation in Nextcloud Server before 20.0.2, 19.0.5, 18.0.11 allows execution of a stored XSS attack using Internet Explorer when saving a 'javascript:' URL in markdown format.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2020-8294",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.2:nextcloud-20.0.7-lp152.3.6.1",
						"openSUSE Leap 15.2:nextcloud-apache-20.0.7-lp152.3.6.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "low"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "3.5",
					"vector_v_2": "AV:N/AC:M/Au:S/C:N/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "5.4",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:C/C:L/I:L/A:N"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/RL6T5BYT4RSAM4DNXPXTDKBKHKKNDVHW/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2020-8294.html",
					"description": "CVE-2020-8294"
				},
				{
					"url": "https://bugzilla.suse.com/1181803",
					"description": "SUSE Bug 1181803"
				}
			]
		},
		{
			"notes": [
				{
					"text": "A wrong check in Nextcloud Server 19 and prior allowed to perform a denial of service attack when resetting the password for a user.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2020-8295",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.2:nextcloud-20.0.7-lp152.3.6.1",
						"openSUSE Leap 15.2:nextcloud-apache-20.0.7-lp152.3.6.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/RL6T5BYT4RSAM4DNXPXTDKBKHKKNDVHW/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2020-8295.html",
					"description": "CVE-2020-8295"
				},
				{
					"url": "https://bugzilla.suse.com/1181804",
					"description": "SUSE Bug 1181804"
				}
			]
		}
	]
}
