{
	"document_title": "Security update for python-Pygments",
	"document_type": "SUSE Patch",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "openSUSE-SU-2021:1402-1"
		},
		"status": "Final",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "1",
				"date": "2021-10-31T14:52:44Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-10-31T14:52:44Z",
		"current_release_date": "2021-10-31T14:52:44Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf.pl",
			"date": "2017-02-24T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "Security update for python-Pygments",
			"title": "Topic",
			"type": "Summary"
		},
		{
			"text": "This update for python-Pygments fixes the following issues:\n\n- CVE-2021-20270: Fixed an infinite loop in the SML lexer (bsc#1183169).\n\nThis update was imported from the SUSE:SLE-15-SP1:Update update project.",
			"title": "Details",
			"type": "General"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		},
		{
			"text": "openSUSE-2021-1402",
			"title": "Patchnames",
			"type": "Details"
		}
	],
	"documentdistribution": "Copyright SUSE LLC under the Creative Commons License 4.0 with Attribution (CC-BY-4.0)",
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/FT4EGNCPUYIMTYR7NYWL7QYVREFIK566/",
			"description": "E-Mail link for openSUSE-SU-2021:1402-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		},
		{
			"type": "Self",
			"url": "https://bugzilla.suse.com/1183169",
			"description": "SUSE Bug 1183169"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/security/cve/CVE-2021-20270/",
			"description": "SUSE CVE CVE-2021-20270 page"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Leap 15.2",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Leap 15.2",
						"full_product_name": {
							"text": "openSUSE Leap 15.2",
							"product_id": "openSUSE Leap 15.2",
							"cpe": "cpe:/o:opensuse:leap:15.2"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python3-Pygments-2.6.1-lp152.5.9.1",
				"full_product_name": {
					"text": "python3-Pygments-2.6.1-lp152.5.9.1",
					"product_id": "python3-Pygments-2.6.1-lp152.5.9.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python3-Pygments-2.6.1-lp152.5.9.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Leap 15.2"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "An infinite loop in SMLLexer in Pygments versions 1.5 to 2.7.3 may lead to denial of service when performing syntax highlighting of a Standard ML (SML) source file, as demonstrated by input that only contains the \"exception\" keyword.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2021-20270",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Leap 15.2:python3-Pygments-2.6.1-lp152.5.9.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.5",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				},
				"scoreset": {}
			},
			"remediations": [
				{
					"type": "Vendor Fix",
					"description": {
						"text": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
						"lang": "en"
					},
					"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/FT4EGNCPUYIMTYR7NYWL7QYVREFIK566/"
				}
			],
			"references": [
				{
					"url": "https://www.suse.com/security/cve/CVE-2021-20270.html",
					"description": "CVE-2021-20270"
				},
				{
					"url": "https://bugzilla.suse.com/1183169",
					"description": "SUSE Bug 1183169"
				}
			]
		}
	]
}
